project:
  type: book
  output-dir: _book

book:
  title: "Rossinante Book"
  author: 
    - name: "Nicolas Casajus"
      orcid: "0000-0002-5537-5294"
      url: "https://nicolascasajus.fr"
      affiliations: 
        - name: FRB-CESAB
          url: "https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/"
  date: today
  description: |
    A user guide to learn how to use the FRB-CESAB server<hr>

  favicon: images/favicon.png
  reader-mode: true
  site-url: https://frbcesab.github.io/rossinante/
  repo-url: https://github.com/frbcesab/rossinante/
  repo-actions: [source, issue]
  
  chapters:
    - index.qmd
    - part: "Get started"
      chapters: 
        - chapters/introduction.qmd
        - chapters/setup.qmd
        - chapters/good-practices.qmd
    - part: "User guide"
      chapters: 
        - chapters/sending-files.qmd
        - chapters/working-with-r.qmd
        - chapters/working-with-python.qmd
        - chapters/working-with-docker.qmd
        - chapters/parallel-computing.qmd
  appendices:
    - chapters/administration.qmd
    - chapters/linux-cheatsheet.qmd
    
  sidebar: 
    logo: images/logo-FRB_CESAB.png
    
  page-footer: 
    left: 
      - text: "This book was built with <a href='https://quarto.org/'>Quarto</a>"
    center: 
      - text: Licensed under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>
    right: 
      - text: 'Code source &nbsp;<i class="bi bi-github" role="img"></i>'
        href: "https://github.com/frbcesab/rossinante"

# bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: true
    execute:
      eval: false
    code-line-numbers: true
    # code-block-bg: true
    # code-block-border-left: "#2780e3"
    highlight-style: zenburn
    reference-location: margin
    toc-depth: 3
    
