# Overview

## Introduction


The FRB-CESAB server **Rossinante** is dedicated to 
scientific computing (see @tbl-hardware for hardware specification). 
It runs under the GNU/Linux distribution **Debian 12** (Bookworm).


**When do you want to use Rossinante?**

- You need to analyse large datasets (RAM operations) and/or,
- You need to repeat tasks many times (parallelization on CPU/GPU).


| **Hardware**                 | **Specifications**                                 |
|------------------------------|----------------------------------------------------|
| CPU                          | `80 threads` (2 x Intel Xeon Gold 5218R)           |
| RAM                          | `384 GB` (12 x Cells 32 Go RDIMM)                  |
| GPU                          | NVIDIA Quadro RTX 6000                             |
| Internal storage             | `6 TB` (8 x 960 GB SSD SATA)                       |
| External storage (Seagate)   | `8 TB` (1 x 8 To HDD USB 3.0 5900 tr/min)          |
| External storage (Cervantes) | `8 TB` (1 x 8 To HDD USB 3.0 5900 tr/min)          |
| External storage (Sancho)    | `8 TB` (1 x 8 To HDD USB 3.0 5900 tr/min)          |


: Hardware specifications {#tbl-hardware}


You can run programs implemented in R, Python, Shell script, C, C++, etc. 
directly from a terminal, using Web clients like [RStudio Server](https://support.posit.co/hc/en-us/articles/200552306-Getting-Started) or 
inside [Docker](https://www.docker.com/) containers.


::: {.callout-important}
## Important

No job scheduling system (e.g. SLURM, Torque) has been installed. This means 
that you can launch jobs whenever you want. However you are invited to respect some rules
(@sec-good-practices).
:::


## Storage

As a regular user, you have access to four personal directories:

- `/home/you/`
- `/media/sancho/you/` (external drive)
- `/media/seagate/you/` (external drive)
- `/media/cervantes/you/` (external drive)

Inside these directories, you can create, edit, rename and remove any files/directories you want.

::: {.callout-important}
## Important

Rossinante is **not a storage server**. The 30 TB storage are shared
among all users. You can store large datasets to run yours
analyses, but once you're done, please remove these files.

**There is no backup system!** You are responsible for your own data.
:::



## Available software

- [`R`](https://cran.r-project.org/) -- Scientific computing (among others)
- [`RStudio Server`](https://www.rstudio.com/products/rstudio/download-server/) -- Web interface for R
- [`Python 3`](https://www.python.org/) -- Scientific computing (among others)
- [`pip3`](https://pip.pypa.io/) -- Python packages managers
- [`venv`](https://docs.python.org/3/library/venv.html) -- Python virtual environments
- [`Pandoc`](https://pandoc.org/) -- Universal document converter
- [`Quarto`](https://quarto.org/) -- Scientific publishing system
- [`git`](https://git-scm.com/) -- Version control system
- [`make`](https://www.gnu.org/software/make/) -- Project compilation
- [`Docker`](https://www.docker.com/) -- Containerization


## Useful utilities

- [`FFmpeg`](https://ffmpeg.org/) -- Transcoding multimedia files
- [`ImageMagick`](https://imagemagick.org) -- Image manipulation program
- [`Poppler`](https://poppler.freedesktop.org/) -- PDF utility library
- [`ExifTool`](https://exiftool.org/) -- File metadata utility
- [`GDAL`](https://gdal.org/), [`GEOS`](https://trac.osgeo.org/geos), [`PROJ`](https://proj.org/) -- Spatial libraries
- [`htop`](https://htop.dev/) -- CPU, RAM, and processes monitoring tool
- [`ctop`](https://github.com/bcicen/ctop) -- Docker containers monitoring tool
- [`nano`](https://www.nano-editor.org/), [`Vim`](https://www.vim.org/) and [`Neovim`](https://neovim.io/) -- CLI text editors
- [`screen`](https://www.gnu.org/software/screen/) and [`tmux`](https://github.com/tmux/tmux/wiki) -- Terminal multiplexers
- [`tree`](http://mama.indstate.edu/users/ice/tree/) -- Recursive directory listing program
- [`curl`](https://curl.se/) and [`wget`](https://www.gnu.org/software/wget/manual/wget.html) -- Download managers
- [`rsync`](https://rsync.samba.org/) -- Incremental file transfer
- [`zip`](https://linuxize.com/post/how-to-zip-files-and-directories-in-linux/) and [`unzip`](https://linuxize.com/post/how-to-unzip-files-in-linux/) -- ZIP files managers
- [`zsh`](https://www.zsh.org/) -- Unix shell (alternative to Bash)
- [`lazygit`](https://github.com/jesseduffield/lazygit) -- CLI interface for git



## Missing software

If you need to use a non-installed software, please contact the administrator.

::: {.callout-note}
## Note on R packages

Each user has a personal R library in which he/she can install every
R packages he/she wants (independently of other users).

For Python, packages are shared among all users except if you work with virtual environments (**recommended**).
:::
